n = input("Digite algo:")
print('O Tipo primitivo de {} é {}'.format(n,type(n)))
print('Só tem espaços?',n.isspace())
print('É um número?',n.isnumeric())
print('É alfabético?',n.isalpha())
print('É alfanumérico?',n.isalnum())
print('Está em maiúsculas?',n.isupper())
print('Está em minúsculas?',n.islower())
print('Está Capitalizada?',n.istitle())